modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
namespace="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/SSWTLZZ69/Create-Vintage-Improvements"
issueTrackerURL="https://github.com/SSWTLZZ69/Create-Vintage-Improvements/issues"
logoFile="logo.png"
credits='''Catchmons, Junnaturefox & Qi-Month - zh_cn localization
padin - en_us localization editing
reds - pt_br localization'''
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.5,6.1.0)"
ordering="NONE"
side="BOTH"
